force-app/main/default/objects/Event_Group_Package__c/Event_Group_Package__c.object-meta.xml
<CustomObject>
    <description>Similar to a price book, the subset of products that should be available for an opportunity and/or event group.</description>
    <label>Event Group Product</label>
    <nameField>
        <displayFormat>EGP-{00000000}</displayFormat>
        <label>EGP Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Group Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Group_Package__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product that is being sold as an event group and/or opportunity package.</description>
    <inlineHelpText>The product that is being sold as an event group and/or opportunity package.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Event_Group_Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Group_Package__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <formula>Product__r.Sales_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Event_Group_Package__c/fields/Team_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Team_Opportunity__c</fullName>
    <description>The team opportunity associated with this event team package. A team opportunity could have a number of packages available for selection by associated passengers.</description>
    <inlineHelpText>The team opportunity associated with this event team package. A team opportunity could have a number of packages available for selection by associated passengers.</inlineHelpText>
    <label>Team Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Event_Team_Packages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan</label>
    <referenceTo>fw1__Payment_Plan__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Team_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Team_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registrations__c/Registrations__c.object-meta.xml
<CustomObject>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{0}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registrations__c/fields/Event_Group_Package__c.field-meta.xml
<CustomField>
    <fullName>Event_Group_Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The event group package selected by the customer during registration.</description>
    <inlineHelpText>The event group package selected by the customer during registration.</inlineHelpText>
    <label>Event Group Package</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This event group package is not available for this event. Please select a different package.</errorMessage>
        <filterItems>
            <field>Event_Group_Package__c.Team_Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <infoMessage>Select desired package.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event_Group_Package__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Room_Type__c.field-meta.xml
<CustomField>
    <fullName>Room_Type__c</fullName>
    <label>Room Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUAD</fullName>
            </value>
            <value>
                <fullName>Triple</fullName>
            </value>
            <value>
                <fullName>Double</fullName>
            </value>
            <value>
                <fullName>Single</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Team_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Team_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Registrations (Team Opportunity)</relationshipLabel>
    <relationshipName>Registrations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RoomTest.cls
@isTest
public class RoomTest {
    @isTest static void RoomTest() {
        
    Account testAccount = new Account();
        testAccount.Name = 'TestAccount';
        insert testAccount;

		Contact ct = new Contact();
		ct.FirstName = 'FName123';
		ct.LastName = 'LName123';
		ct.Email = 'fff1223@test.com';
        ct.MobilePhone = '121';
        ct.MailingStreet = 'test.com';
        ct.MailingCity = 'BNG';
        ct.MailingState = 'New';
        ct.MailingPostalCode = '112121';
        ct.AccountId = testAccount.Id;
        
        insert ct;
        system.debug('CT id: '+ct);
        fw1__Payment_Plan__c pyt = new fw1__Payment_Plan__c(fw1__Schedule__c='Daily',fw1__Installment_Fee__c=100);
        insert pyt;
       Opportunity opId = new Opportunity(Payment_Plan__c=pyt.Id,AccountId=testAccount.Id,Name = 'ETTest',StageName='Value Proposition',OwnerId=UserInfo.getUserId(),CloseDate = Date.newinstance(2022, 2, 17));
       insert opId;
    Product2 prod = new Product2(Name = 'Laptop X200',Family = 'Hardware',Description='HjhJHjsds sdss',Sales_Price__c=33.33,
                                    Room_Type__c='2');
    insert prod;
    Event_Group_Package__c eventGP  = new Event_Group_Package__c(Product__c=prod.Id,Team_Opportunity__c=opId.Id);
    insert eventGP;
        Test.startTest();
    Room rm = new Room();
    rm.eventPackage = eventGP;
    rm.packageQuantity = 2;
    rm.persons = new List<Registrations__c>();
    rm.personsCount = new List<SelectOption>();
    rm.roomNo = 2;
    rm.selectedpersonsCount=1;
        System.assertNotEquals(null, rm);
        Test.stopTest();
    }
}