force-app/main/default/objects/Event_Group_Package__c/Event_Group_Package__c.object-meta.xml
<CustomObject>
    <description>Similar to a price book, the subset of products that should be available for an opportunity and/or event group.</description>
    <label>Event Group Product</label>
    <nameField>
        <displayFormat>EGP-{00000000}</displayFormat>
        <label>EGP Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Group Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registrations__c/Registrations__c.object-meta.xml
<CustomObject>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{0}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registrations__c/fields/Event_Group_Package__c.field-meta.xml
<CustomField>
    <fullName>Event_Group_Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The event group package selected by the customer during registration.</description>
    <inlineHelpText>The event group package selected by the customer during registration.</inlineHelpText>
    <label>Event Group Package</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This event group package is not available for this event. Please select a different package.</errorMessage>
        <filterItems>
            <field>Event_Group_Package__c.Team_Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <infoMessage>Select desired package.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event_Group_Package__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Room.cls
public class Room{
    @AuraEnabled
    public Integer packageQuantity{get;set;}
    @AuraEnabled
    public Integer roomNo{get;set;}
    @AuraEnabled
    public List<Registrations__c> persons{get;set;}
  
    public List<SelectOption> personsCount{get;set;}
    @AuraEnabled
    public Integer selectedpersonsCount{get;set;}
    @AuraEnabled
    public Event_Group_Package__c eventPackage{get;set;}
    
    
}