force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>KSA Quote</label>
    <nameField>
        <displayFormat>Q-{0000000}</displayFormat>
        <label>Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>American Express</fullName>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
            <value>
                <fullName>MasterCard</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Registration_Opportunities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/CVV__c.field-meta.xml
<CustomField>
    <fullName>CVV__c</fullName>
    <label>CVV</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount__c</fullName>
    <label>Paid Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Registrations__c/Registrations__c.object-meta.xml
<CustomObject>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{0}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registrations__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>400.00</defaultValue>
    <inlineHelpText>$400.00 Per Person</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>American Express</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
            <value>
                <fullName>MasterCard</fullName>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/CVV__c.field-meta.xml
<CustomField>
    <fullName>CVV__c</fullName>
    <label>CVV</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Exp_Date__c.field-meta.xml
<CustomField>
    <fullName>Exp_Date__c</fullName>
    <label>Exp Date</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/State_Providence__c.field-meta.xml
<CustomField>
    <fullName>State_Providence__c</fullName>
    <label>State / Providence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama-AL</fullName>
            </value>
            <value>
                <fullName>Alaska-AK</fullName>
            </value>
            <value>
                <fullName>Arizona-AZ</fullName>
            </value>
            <value>
                <fullName>Arkansas-AR</fullName>
            </value>
            <value>
                <fullName>California-CA</fullName>
            </value>
            <value>
                <fullName>Colorado-CO</fullName>
            </value>
            <value>
                <fullName>Connecticut-CT</fullName>
            </value>
            <value>
                <fullName>Delaware-DE</fullName>
            </value>
            <value>
                <fullName>District of Columbia-DC</fullName>
            </value>
            <value>
                <fullName>Florida-FL</fullName>
            </value>
            <value>
                <fullName>Georgia-GA</fullName>
            </value>
            <value>
                <fullName>Hawaii-HI</fullName>
            </value>
            <value>
                <fullName>Idaho-ID</fullName>
            </value>
            <value>
                <fullName>Illinois-IL</fullName>
            </value>
            <value>
                <fullName>Indiana-IN</fullName>
            </value>
            <value>
                <fullName>Iowa-IA</fullName>
            </value>
            <value>
                <fullName>Kansas-KS</fullName>
            </value>
            <value>
                <fullName>Kentucky-KY</fullName>
            </value>
            <value>
                <fullName>Louisiana-LA</fullName>
            </value>
            <value>
                <fullName>Maine-ME</fullName>
            </value>
            <value>
                <fullName>Maryland-MD</fullName>
            </value>
            <value>
                <fullName>Massachusetts-MA</fullName>
            </value>
            <value>
                <fullName>Michigan-MI</fullName>
            </value>
            <value>
                <fullName>Minnesota-MN</fullName>
            </value>
            <value>
                <fullName>Mississippi-MS</fullName>
            </value>
            <value>
                <fullName>Missouri-MO</fullName>
            </value>
            <value>
                <fullName>Montana-MT</fullName>
            </value>
            <value>
                <fullName>Nebraska-NE</fullName>
            </value>
            <value>
                <fullName>Nevada-NV</fullName>
            </value>
            <value>
                <fullName>New Hampshire-NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KSA_PaymentCtrl.cls
public without sharing class KSA_PaymentCtrl {
   /* @AuraEnabled
    public static PaymentResponse processPayment(String recordId)
    {
        Registrations__c reg = [Select Id,Name,First_Name__c,Last_Name__c,Email__c,Amount__c,
                                Mobile__c,Street__c,City__c,State_Providence__c,Postal_Code__c,
                                Credit_Card_Number__c,Exp_Date__c,
                                CVV__c
                                FROM Registrations__c 
                                WHERE Id=:recordId LIMIT 1];
        PaymentCenterSampleCodes.amount = reg.Amount__c;
        PaymentCenterSampleCodes.billingCity = reg.City__c;
        PaymentCenterSampleCodes.billingCountry = 'US';
        PaymentCenterSampleCodes.billingEmail = reg.Email__c;
        PaymentCenterSampleCodes.billingPostalCode = reg.Postal_Code__c;
        PaymentCenterSampleCodes.billingState = reg.State_Providence__c;
        PaymentCenterSampleCodes.billingStreet = reg.Street__c;
        PaymentCenterSampleCodes.cardNumber = reg.Credit_Card_Number__c;
        PaymentCenterSampleCodes.expMonth = '12';
        PaymentCenterSampleCodes.expYear = '2021';
        PaymentCenterSampleCodes.firstName = reg.First_Name__c;
        PaymentCenterSampleCodes.lastName = reg.Last_Name__c;
        PaymentCenterSampleCodes.paymentName = reg.Name;
        return PaymentCenterSampleCodes.payNow();
    }
    
    //@future(callout=true)
    public static void processQuotePayment(Id quoteId)
    {
        Quote__c quote = [Select Id,Name,Contact__r.FirstName,Contact__r.LastName,Contact__r.Email,
                                Contact__r.MailingStreet,Contact__r.MailingState,Contact__r.MailingCity,
                                Contact__r.MailingPostalCode,
                                Card_Type__c,Credit_Card_Number__c,Exp_Date__c,
                                CVV__c,Paid_Amount__c
                                FROM Quote__c 
                                WHERE Id=:quoteId LIMIT 1];
        
        PaymentCenterSampleCodes.amount = quote.Paid_Amount__c;
        PaymentCenterSampleCodes.billingCity = quote.Contact__r.MailingCity;
        PaymentCenterSampleCodes.billingCountry = 'US';
        PaymentCenterSampleCodes.billingEmail = quote.Contact__r.Email;
        PaymentCenterSampleCodes.billingPostalCode = quote.Contact__r.MailingPostalCode;
        PaymentCenterSampleCodes.billingState = quote.Contact__r.MailingState;
        PaymentCenterSampleCodes.billingStreet = quote.Contact__r.MailingStreet;
        PaymentCenterSampleCodes.cardNumber = quote.Credit_Card_Number__c;
        PaymentCenterSampleCodes.expMonth = '12';
        PaymentCenterSampleCodes.expYear = '2021';
        PaymentCenterSampleCodes.firstName = quote.Contact__r.FirstName;
        PaymentCenterSampleCodes.lastName = quote.Contact__r.LastName;
        PaymentCenterSampleCodes.paymentName = quote.Name;
        PaymentResponse res =  PaymentCenterSampleCodes.payNow();
        System.debug(res);
        if(res.IsSuccessful == false)
        {
            throw new UtilityException(res.Message); 
        } 
        else if(res.IsSuccessful == true)
        {
            if(!Test.isRunningTest()){
            	throw new UtilityException('Success transaction.'); 
            }
        } 
    }
    @AuraEnabled    
    public static Registrations__c getRecordDetails(String recordId)
    {
        Registrations__c reg = [Select Id,Name,First_Name__c,Last_Name__c,Email__c,Amount__c,
                                Mobile__c,Street__c,City__c,State_Providence__c,Postal_Code__c,
                                Credit_Card_Number__c,Exp_Date__c,
                                CVV__c
                                FROM Registrations__c 
WHERE Id=:recordId LIMIT 1];
return reg;
}*/
    @AuraEnabled
    public static PaymentResponse processPayment(Decimal amount,String cardNumber,String expMonth,String expYear, String CVV,
                                                 String billingStreet,String billingCity,String billingState,
                                                 String billingPostalCode,
                                                 String billingCountry,String billingEmail,String billingFirstName,
                                                 String billingLastName,
                                                 String paymentName, String description)
    { 
        PaymentCenterSampleCodes.amount = amount;
        PaymentCenterSampleCodes.billingStreet = billingStreet;
        PaymentCenterSampleCodes.billingCity = billingCity;
        PaymentCenterSampleCodes.billingState = billingState;
        PaymentCenterSampleCodes.billingPostalCode = billingPostalCode;
        PaymentCenterSampleCodes.billingCountry = billingCountry;
        PaymentCenterSampleCodes.billingEmail = billingEmail;
        
        
        
        PaymentCenterSampleCodes.cardNumber = cardNumber;
        PaymentCenterSampleCodes.expMonth = expMonth;
        PaymentCenterSampleCodes.expYear = expYear;
        PaymentCenterSampleCodes.CVV = CVV;
        PaymentCenterSampleCodes.firstName = billingFirstName;
        PaymentCenterSampleCodes.lastName = billingFirstName;
        PaymentCenterSampleCodes.paymentName = paymentName;
        PaymentCenterSampleCodes.description = description;
        return PaymentCenterSampleCodes.payNow();
    }
}