force-app/main/default/objects/Opportunity/fields/Arrival_Date__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Date__c</fullName>
    <label>Arrival Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <label>Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Team Billing</fullName>
            </value>
            <value>
                <fullName>Individual Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Double_Room__c.field-meta.xml
<CustomField>
    <fullName>Double_Room__c</fullName>
    <description>Number of Doubles for this Opportunity</description>
    <label>Double Room</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/KSA_Webcode__c.field-meta.xml
<CustomField>
    <fullName>KSA_Webcode__c</fullName>
    <formula>X2_Digit_Year__c + Sport_Abbreviation__c + Code_Auto_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>KSA Webcode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/KSASport_or_Performing_Art__c.field-meta.xml
<CustomField>
    <fullName>KSASport_or_Performing_Art__c</fullName>
    <label>Sport or Performing Art</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Athletic Director</fullName>
            </value>
            <value>
                <fullName>Baseball</fullName>
            </value>
            <value>
                <fullName>Boys Basketball</fullName>
            </value>
            <value>
                <fullName>Boys Golf</fullName>
            </value>
            <value>
                <fullName>Boys Lacrosse</fullName>
            </value>
            <value>
                <fullName>Boys Tennis</fullName>
            </value>
            <value>
                <fullName>Cheer and Dance</fullName>
            </value>
            <value>
                <fullName>Chorus</fullName>
            </value>
            <value>
                <fullName>Cross Country</fullName>
            </value>
            <value>
                <fullName>Field Hockey</fullName>
            </value>
            <value>
                <fullName>Flag Football</fullName>
            </value>
            <value>
                <fullName>Football</fullName>
            </value>
            <value>
                <fullName>Girls Basketball</fullName>
            </value>
            <value>
                <fullName>Girls Golf</fullName>
            </value>
            <value>
                <fullName>Girls Lacrosse</fullName>
            </value>
            <value>
                <fullName>Girls Leadership</fullName>
            </value>
            <value>
                <fullName>Girls Tennis</fullName>
            </value>
            <value>
                <fullName>Instrumental</fullName>
            </value>
            <value>
                <fullName>Music</fullName>
            </value>
            <value>
                <fullName>Softball</fullName>
            </value>
            <value>
                <fullName>Track and Field</fullName>
            </value>
            <value>
                <fullName>Volleyball</fullName>
            </value>
            <value>
                <fullName>Wrestling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Quad_Rooms__c.field-meta.xml
<CustomField>
    <fullName>Quad_Rooms__c</fullName>
    <description>Number of Quad rooms for this Opportunity</description>
    <label>Quad Rooms</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/School_Contact__c.field-meta.xml
<CustomField>
    <fullName>School_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>KSA Opportunity</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Single_Room__c.field-meta.xml
<CustomField>
    <fullName>Single_Room__c</fullName>
    <description>Number of Single Rooms for this Opportunity</description>
    <label>Single Room</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Team_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Team_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Triple_Room__c.field-meta.xml
<CustomField>
    <fullName>Triple_Room__c</fullName>
    <description>Number of Triples for this Opportunity</description>
    <label>Triple Room</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rooms__c/Rooms__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Rooms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rooms__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Single</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Double</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Triple</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Quad</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Six</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/roomBuilderTest.cls
/* ─────────────────────────────────────────────────────────────────────────────────────────────────
 * TITLE:          roomBuilderTest apex
 * DESCRIPTION:    Pulls/creates the least amount of rooms for all the athletes for a given a webcode
 * @created        03/24/2025
 * @updated
 * @by             FTC       hey@freethinkersconsulting.com
 * ──────────────────────────────────────────────────────────────────────────────────────────────────
 * @notes:
 */

@isTest
private class roomBuilderTest {
  @TestSetup
  static void makeData() {
    Account acc = new Account(Name = 'Test Account');
    insert acc;
    // Create an account
    Opportunity parentOpp = new Opportunity(
      AccountId = acc.Id,
      Name = 'Parent Opp',
      StageName = 'Inquiry',
      CloseDate = Date.today()
    );
    insert parentOpp;
    // These opps should create (2, 4 sized rooms), (1, 2 sized room), (2, 3 sized rooms), 2, (2, 1 sized room)
    // Data creation
    List<String> studentNames = new List<String>{
      'Alice',
      'Bob',
      'Charlie',
      'David',
      'Eve',
      'Frank',
      'Grace',
      'Hannah',
      'Ivy',
      'Jack',
      'Kara',
      'Liam',
      'Mona'
    };
    List<Contact> contactList = new List<Contact>();
    for (Integer i = 0; i < studentNames.size(); i++) {
      Contact con = new Contact(LastName = studentNames[i], AccountId = acc.Id);
      contactList.add(con);
    }
    insert contactList;
    List<Decimal> roomNums = new List<Decimal>{
      0.25,
      0.25,
      0.25,
      0.25,
      0.25,
      0.5,
      0.5,
      1,
      0.33,
      0.3,
      0.3,
      0.3,
      1
    };

    Integer i = 0;
    List<Opportunity> opps = new List<Opportunity>();
    for (Decimal num : roomNums) {
      Opportunity opp = new Opportunity(
        Name = studentNames[i],
        School_Contact__c = contactList[i].Id,
        AccountId = acc.Id,
        Arrival_Date__c = Date.today(),
        KSASport_or_Performing_Art__c = 'Volleyball',
        StageName = 'Inquiry',
        CloseDate = Date.today(),
        Team_Opportunity__c = parentOpp.Id,
        Billing_Type__c = 'Individual Billing',
        RecordTypeId = '012f4000000aRkUAAU' // athlete record type
      );

      if (num == 0.25) {
        opp.Quad_Rooms__c = num;
      } else if (num >= 0.3 && num <= 0.34) {
        opp.Triple_Room__c = num;
      } else if (num == 0.5) {
        opp.Double_Room__c = num;
      } else if (num == 1) {
        opp.Single_Room__c = num;
      }
      opps.add(opp);
      i++;
    }
    insert opps;
  }

  @isTest
  static void testFirstRun() {
    // TO DO: implement unit test
    Opportunity parentOpp = [
      SELECT Id, KSA_Webcode__c
      FROM Opportunity
      WHERE RecordTypeId != '012f4000000aRkUAAU'
    ];
    roomBuilder.AthletesAndRooms resp = roomBuilder.getAthletesAndRooms(
      parentOpp.KSA_Webcode__c
    );
    List<Rooms__c> rooms = resp.rooms;
    System.assertEquals(7, rooms.size());
    List<Rooms__c> allRooms = [SELECT Id FROM Rooms__c];
    System.assertEquals(7, allRooms.size());
    Integer room4Cnt = 0;
    Integer room3Cnt = 0;
    Integer room2Cnt = 0;
    Integer room1Cnt = 0;
    for (Rooms__c room : rooms) {
      String roomType = room.Type__c;
      if (roomType == '4') {
        room4Cnt++;
      } else if (roomType == '3') {
        room3Cnt++;
      } else if (roomType == '2') {
        room2Cnt++;
      } else if (roomType == '1') {
        room1Cnt++;
      }
    }
    // These values come from the comment in the testSetup method
    System.assertEquals(2, room4Cnt);
    System.assertEquals(2, room3Cnt);
    System.assertEquals(1, room2Cnt);
    System.assertEquals(2, room1Cnt);
  }

  // Will delete one of the Quad preference opportunities and reduce our room cnt down to 1 for quad rooms
  @isTest
  static void testDeleteMemberAfterRoomsAreCreated() {
    // TO DO: implement unit test
    Opportunity parentOpp = [
      SELECT Id, KSA_Webcode__c
      FROM Opportunity
      WHERE RecordTypeId != '012f4000000aRkUAAU'
    ];
    roomBuilder.getAthletesAndRooms(parentOpp.KSA_Webcode__c);
    Opportunity deleteQuad = [SELECT Id FROM Opportunity WHERE Quad_Rooms__c = 0.25 LIMIT 1];
    delete deleteQuad;

    roomBuilder.AthletesAndRooms resp = roomBuilder.getAthletesAndRooms(
      parentOpp.KSA_Webcode__c
    );
    List<Rooms__c> rooms = resp.rooms;
    System.assertEquals(6, rooms.size());
    List<Rooms__c> allRooms = [SELECT Id FROM Rooms__c];
    System.assertEquals(6, allRooms.size());
    Integer room4Cnt = 0;
    Integer room3Cnt = 0;
    Integer room2Cnt = 0;
    Integer room1Cnt = 0;
    for (Rooms__c room : rooms) {
      String roomType = room.Type__c;
      if (roomType == '4') {
        room4Cnt++;
      } else if (roomType == '3') {
        room3Cnt++;
      } else if (roomType == '2') {
        room2Cnt++;
      } else if (roomType == '1') {
        room1Cnt++;
      }
    }
    // These values come from the comment in the testSetup method
    System.assertEquals(1, room4Cnt);
    System.assertEquals(2, room3Cnt);
    System.assertEquals(1, room2Cnt);
    System.assertEquals(2, room1Cnt);
  }


  // Add an extra opp for Doubles. Will require +1 Double room
  @isTest
  static void testNewMemberAfterFirstRun() {
    Opportunity parentOpp = [
      SELECT Id, KSA_Webcode__c
      FROM Opportunity
      WHERE RecordTypeId != '012f4000000aRkUAAU'
    ];
    roomBuilder.AthletesAndRooms resp = roomBuilder.getAthletesAndRooms(
      parentOpp.KSA_Webcode__c
    );

    Account acc = [SELECT Id FROM Account];
    Opportunity opp = new Opportunity(
      Double_Room__c = 0.5,
      Name = 'asdf',
      AccountId = acc.Id,
      Arrival_Date__c = Date.today(),
      KSASport_or_Performing_Art__c = 'Volleyball',
      StageName = 'Inquiry',
      CloseDate = Date.today(),
      Team_Opportunity__c = parentOpp.Id,
      Billing_Type__c = 'Individual Billing',
      RecordTypeId = '012f4000000aRkUAAU' // athlete record type
    );
    insert opp;

    resp = roomBuilder.getAthletesAndRooms(parentOpp.KSA_Webcode__c);
    List<Rooms__c> rooms = resp.rooms;
    System.assertEquals(8, rooms.size());
    List<Rooms__c> allRooms = [SELECT Id FROM Rooms__c];
    System.assertEquals(8, allRooms.size());
    Integer room4Cnt = 0;
    Integer room3Cnt = 0;
    Integer room2Cnt = 0;
    Integer room1Cnt = 0;
    for (Rooms__c room : rooms) {
      String roomType = room.Type__c;
      if (roomType == '4') {
        room4Cnt++;
      } else if (roomType == '3') {
        room3Cnt++;
      } else if (roomType == '2') {
        room2Cnt++;
      } else if (roomType == '1') {
        room1Cnt++;
      }
    }
    // These values come from the comment in the testSetup method + 1 more since we're adding another 2nd room athlete
    System.assertEquals(2, room4Cnt);
    System.assertEquals(2, room3Cnt);
    System.assertEquals(2, room2Cnt);       // 1 more double room
    System.assertEquals(2, room1Cnt);
  }

  @isTest
  static void testUpdate() {
    Opportunity opp = [SELECT Id, KSA_Webcode__c FROM Opportunity LIMIT 1];
    roomBuilder.updateAthletes(new List<Opportunity>{ opp });
  }

  // Todo - Update above tests to check that room numbering stays ordered and no duplicates are re-created
}