force-app/main/default/objects/Opportunity/fields/fw1__Total_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>fw1__Total_Invoice_Amount__c</fullName>
    <label>Total Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/fw1__Total_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>fw1__Total_Paid_Amount__c</fullName>
    <label>Total Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/KSA_Webcode__c.field-meta.xml
<CustomField>
    <fullName>KSA_Webcode__c</fullName>
    <formula>X2_Digit_Year__c + Sport_Abbreviation__c + Code_Auto_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>KSA Webcode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Rooms__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SportName__c.field-meta.xml
<CustomField>
    <fullName>SportName__c</fullName>
    <label>SportName</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Baseball</fullName>
            </value>
            <value>
                <fullName>Boys Basketball</fullName>
            </value>
            <value>
                <fullName>Boys Lacrosse</fullName>
            </value>
            <value>
                <fullName>Cheer and Dance</fullName>
            </value>
            <value>
                <fullName>Chorus</fullName>
            </value>
            <value>
                <fullName>Cross Country</fullName>
            </value>
            <value>
                <fullName>Field Hockey</fullName>
            </value>
            <value>
                <fullName>Flag Football</fullName>
            </value>
            <value>
                <fullName>Football</fullName>
            </value>
            <value>
                <fullName>Girls Basketball</fullName>
            </value>
            <value>
                <fullName>Girls Lacrosse</fullName>
            </value>
            <value>
                <fullName>Girls Leadership</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Instrumental</fullName>
            </value>
            <value>
                <fullName>Music</fullName>
            </value>
            <value>
                <fullName>Softball</fullName>
            </value>
            <value>
                <fullName>Tennis</fullName>
            </value>
            <value>
                <fullName>Track and Field</fullName>
            </value>
            <value>
                <fullName>Volleyball</fullName>
            </value>
            <value>
                <fullName>Wrestling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>KSA Quote</label>
    <nameField>
        <displayFormat>Q-{0000000}</displayFormat>
        <label>Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Registration_Opportunities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Is_Head_Coach__c.field-meta.xml
<CustomField>
    <fullName>Is_Head_Coach__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Head Coach</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Registration_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount__c</fullName>
    <label>Paid Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_By__c.field-meta.xml
<CustomField>
    <fullName>Quote_By__c</fullName>
    <label>Quote By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ATHLETE</fullName>
            </value>
            <value>
                <fullName>COACH</fullName>
            </value>
            <value>
                <fullName>TAG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Partly Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <summarizedField>Registration_Line_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Registration_Line_Item__c.Quote__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Registrations__c/Registrations__c.object-meta.xml
<CustomObject>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{0}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registrations__c/fields/Assigned_Room__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Room</label>
    <referenceTo>Rooms__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Room_No__c.field-meta.xml
<CustomField>
    <fullName>Room_No__c</fullName>
    <label>Room No</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registrations__c/recordTypes/COACH.recordType-meta.xml
<RecordType>
    <fullName>COACH</fullName>
    <active>true</active>
    <description>COACH</description>
    <label>COACH</label>
</RecordType>

force-app/main/default/objects/Registrations__c/recordTypes/TAG.recordType-meta.xml
<RecordType>
    <fullName>TAG</fullName>
    <active>true</active>
    <description>Tag-along fan</description>
    <label>TAG</label>
</RecordType>

force-app/main/default/objects/Rooms__c/Rooms__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Rooms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rooms__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rooms__c/fields/Room_No__c.field-meta.xml
<CustomField>
    <fullName>Room_No__c</fullName>
    <label>Room No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rooms__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Single</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Double</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Triple</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Quad</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Six</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KSAQuotesCtrl.cls
public without sharing class KSAQuotesCtrl {
    
    /*@AuraEnabled
    public static QuoteWrapper getQuotes(String contactId) {
        QuoteWrapper qWrapper = new QuoteWrapper();
        Set<String> setWebCodes = new Set<String>();
        List<Quote__c> quotes = [Select Id, Name, Opportunity__r.Name,Paid_Amount__c, Total_Amount__c, Opportunity__r.KSA_Webcode__c, Status__c, Quote_By__c, is_Head_Coach__c
                                 from Quote__c where Contact__c=:contactId];
        qWrapper.quotes = quotes;
        for(Quote__c q : quotes) {
            if((q.Quote_By__c == 'COACH') && q.is_Head_Coach__c) {
                setWebCodes.add(q.Opportunity__r.KSA_Webcode__c);
            }
        }
        if(!setWebCodes.isEmpty()) {
            qWrapper.otherQuotes = getQuotesForCoach(setWebCodes, contactId);
        }
        return qWrapper;
    }
    
    public static Map<String, List<Quote__c>> getQuotesForCoach(Set<String> setWebCode, String conId) {
        Map<String, List<Quote__c>> mapWebcodeQuoteList = new Map<String, List<Quote__c>>();
        
        List<Quote__c> quotes = [Select Id, Name, Opportunity__r.Name, Contact__r.Name, Paid_Amount__c, Total_Amount__c, Opportunity__r.KSA_Webcode__c, Status__c, Quote_By__c
                                 from Quote__c where Opportunity__r.KSA_Webcode__c in :setWebCode and (Contact__c <> :conId)];
        for(Quote__c q : quotes) {
            if(!mapWebcodeQuoteList.containsKey(q.Opportunity__r.Name)) {
                mapWebcodeQuoteList.put(q.Opportunity__r.Name, new List<Quote__c>{q});
            } else {
                List<Quote__c> tempQuoteList = mapWebcodeQuoteList.get(q.Opportunity__r.Name);
                tempQuoteList.add(q);
                mapWebcodeQuoteList.put(q.Opportunity__r.Name, tempQuoteList);
            }
        }
        return mapWebcodeQuoteList;
    }
    
    @AuraEnabled
    public static List<fw1__Invoice__c> getInvoices(String contactId) {
        Set<Id> setQuoteId = new Set<Id>();
        for(Quote__c quotes : [Select Id, Name from Quote__c where Contact__c=:contactId]) {
            setQuoteId.add(quotes.Id);
        }

        List<fw1__Invoice__c> lstInvoice = [Select id, fw1__Account__r.Name, fw1__Opportunity__r.Name, fw1__Invoice_Date__c,
                                            fw1__Total_Invoice_Amount__c, fw1__Total_Paid_Amount__c, fw1__Balance_Due__c
                                            from fw1__Invoice__c where Quote__c in :setQuoteId];
        
        return lstInvoice;
    }
    
    @AuraEnabled
    public static List<fw1__Invoice__c> getManualInvoices(String contactId) {
        Set<Id> setOppId = new Set<Id>();
        String coachRec = Schema.getGlobalDescribe().get('Registrations__c').getDescribe().getRecordTypeInfosByName().get('COACH').getRecordTypeId();
        List<Registrations__c> lstReg = [Select id, Opportunity__c, Quote__r.is_Head_Coach__c from Registrations__c where Contact__c = :contactId and RecordTypeId = :coachRec];
        
        if(!lstReg.isEmpty()) {
            for(Registrations__c objReg : lstReg) {
                if(objReg.Quote__r.is_Head_Coach__c) {
                    setOppId.add(objReg.Opportunity__c);
                }
            }
        }
        
        List<fw1__Invoice__c> lstInvoice = [Select id, fw1__Account__r.Name, fw1__Opportunity__r.Name, fw1__Invoice_Date__c,
                                            fw1__Total_Invoice_Amount__c, fw1__Total_Paid_Amount__c, fw1__Balance_Due__c
                                            from fw1__Invoice__c where fw1__Opportunity__c in :setOppId and Quote__c = null];
        
        
        return lstInvoice;
    }
    
    @AuraEnabled
    public static List<fw1__Invoice_Line__c> getInvoiceLine(String invoiceId) {
        return [Select id, fw1__Product2__r.Name, fw1__Unit_Price__c, fw1__Quantity__c, fw1__Amount__c from fw1__Invoice_Line__c where fw1__Invoice__c = :invoiceId];
    }
    
    @AuraEnabled
    public static List<fw1__Payment__c> getPaymentInfo(String invoiceId) {
        return[Select id, fw1__Amount__c, fw1__Payment_Method__c, fw1__Payment_Date__c, fw1__Status__c, fw1__Total_Paid_Amount__c from fw1__Payment__c where fw1__Invoice__c = :invoiceId];
    }
    
    @AuraEnabled
    public static List<opportunity> getCoachEventInfo(String contactId) {
        Set<Id> setOppId = new Set<Id>();
        String coachRec = Schema.getGlobalDescribe().get('Registrations__c').getDescribe().getRecordTypeInfosByName().get('COACH').getRecordTypeId();
        List<Registrations__c> lstReg = [Select id, Opportunity__c, Quote__r.is_Head_Coach__c  from Registrations__c where Contact__c = :contactId and RecordTypeId = :coachRec];
        
        if(!lstReg.isEmpty()) {
            for(Registrations__c objReg : lstReg) {
                if(objReg.Quote__r.is_Head_Coach__c) {
                    setOppId.add(objReg.Opportunity__c);
                }
            }
        }
        
        List<Opportunity> lstOpp = [Select id, account.Name, Name, SportName__c from opportunity where id = :setOppId and CloseDate > :system.today()];
        
        return lstOpp;
    }
    
    @AuraEnabled
    public static RoomingListWrapper getRoomingListInfo(String opportunityId) {
        RoomingListWrapper roomingWrapper = new RoomingListWrapper();
        List<PickListWrapper> lstRegWrapper = new List<PickListWrapper>();
        Map<String, List<String>> mapRoomPersons = new Map<String, List<String>>();
        String tagRec = Schema.getGlobalDescribe().get('Registrations__c').getDescribe().getRecordTypeInfosByName().get('TAG').getRecordTypeId();
        
        lstRegWrapper.add(new PickListWrapper('','-- None --'));

        for(Registrations__c reg : [Select id, First_Name__c, Last_Name__c, Assigned_Room__c from Registrations__c where Opportunity__c = :opportunityId and RecordTypeId <> :tagRec order by First_Name__c ]) {
            lstRegWrapper.add(new PickListWrapper(reg.Id, reg.First_Name__c +' '+reg.Last_Name__c));
            
            List<String> lstTempId;
            if(mapRoomPersons.containsKey(reg.Assigned_Room__c)) {
                lstTempId = mapRoomPersons.get(reg.Assigned_Room__c);
            } else {
                lstTempId = new List<String>();
            }
            
            lstTempId.add(reg.Id);
            mapRoomPersons.put(reg.Assigned_Room__c, lstTempId);
        }
        
        List<RoomWrapper> lstRoomWrapper = new List<RoomWrapper>();
        for(Rooms__c objRoom : [Select id, Room_No__c, Type__c from Rooms__c where Opportunity__c = :opportunityId order by Room_No__c]) {
            RoomWrapper objRoomWrapper = new RoomWrapper();
            if(mapRoomPersons.containsKey(objRoom.Id)) {
                integer limitRoomSize = (Integer.valueOf(objRoom.Type__c) - (mapRoomPersons.get(objRoom.Id).size()));
                for(integer i = 0; i < limitRoomSize; i++) {
                    mapRoomPersons.get(objRoom.Id).add('');
                }
            } else {
                List<String> lstTempId = new List<String>();
                for(integer i = 0; i < Integer.valueOf(objRoom.Type__c); i++) {
                    lstTempId.add('');  
                } 
                mapRoomPersons.put(objRoom.Id, lstTempId);
            }
            objRoomWrapper.room = objRoom;
            objRoomWrapper.selectedRegList = mapRoomPersons.get(objRoom.Id);
            lstRoomWrapper.add(objRoomWrapper);
        }
        
        roomingWrapper.rooms = lstRoomWrapper;
        roomingWrapper.regList = lstRegWrapper;
        system.debug(roomingWrapper);
        return roomingWrapper;
    }
    
    @AuraEnabled
    public static String updateRoomingListInfo(Map<String, String> mapRoomIdRegId, String oppId) {
        String response ='';
        List<Registrations__c> lstReg = new List<Registrations__c>();
        try {
            for(Registrations__c reg : [Select id, Assigned_Room__c from Registrations__c where Opportunity__c = :oppId]) {
                if(mapRoomIdRegId.containsKey(reg.Id)) {
                    reg.Assigned_Room__c = mapRoomIdRegId.get(reg.Id);
                } else {
                    reg.Assigned_Room__c =null;
                }
                
                lstReg.add(reg);
            }
            if(!lstReg.isEmpty()) {
                update lstReg;
            }
            response = 'Succefully assigned rooms to persons.';
        } catch(Exception ex) {
            response = ex.getMessage()+' '+ex.getStackTraceString();
        }
        return response;
    }
    
    public class QuoteWrapper {
        @AuraEnabled
        public List<Quote__c> quotes;
        @AuraEnabled
        public Map<String, List<Quote__c>> otherQuotes;
    }
    
    public class RoomingListWrapper {
        @AuraEnabled public List<RoomWrapper> rooms { get; set; }
        @AuraEnabled public List<Map<String,String>> regList { get; set; }
        
        public RoomingListWrapper() {
            rooms = new List<RoomWrapper>();
            regList = new List<Map<String,String>>();
        }
    }
    
    public class RoomWrapper {
        @AuraEnabled public Room__c room { get; set; }
        @AuraEnabled public List<String> selectedRegList { get; set; }
        
        public RoomWrapper() {
            selectedRegList = new List<String>();
        }
    }
    
    public class PickListWrapper {
        @AuraEnabled
        public String value;
        @AuraEnabled
        public String label;
        
        public PickListWrapper(String val, String lbl) {
            this.value = val;
            this.label = lbl;
        }
    }
    
    public static void codeCoverage() {
        integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }*/
}