force-app/main/default/objects/Opportunity/fields/KSA_Webcode__c.field-meta.xml
<CustomField>
    <fullName>KSA_Webcode__c</fullName>
    <formula>X2_Digit_Year__c + Sport_Abbreviation__c + Code_Auto_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>KSA Webcode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan</label>
    <referenceTo>fw1__Payment_Plan__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>KSA Quote</label>
    <nameField>
        <displayFormat>Q-{0000000}</displayFormat>
        <label>Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>American Express</fullName>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
            <value>
                <fullName>MasterCard</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Registration_Opportunities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/CVV__c.field-meta.xml
<CustomField>
    <fullName>CVV__c</fullName>
    <label>CVV</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Is_Head_Coach__c.field-meta.xml
<CustomField>
    <fullName>Is_Head_Coach__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Head Coach</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Registration_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount__c</fullName>
    <label>Paid Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan</label>
    <referenceTo>fw1__Payment_Plan__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_By__c.field-meta.xml
<CustomField>
    <fullName>Quote_By__c</fullName>
    <label>Quote By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ATHLETE</fullName>
            </value>
            <value>
                <fullName>COACH</fullName>
            </value>
            <value>
                <fullName>TAG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registrations__c/Registrations__c.object-meta.xml
<CustomObject>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{0}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registrations__c/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>American Express</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
            <value>
                <fullName>MasterCard</fullName>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/CVV__c.field-meta.xml
<CustomField>
    <fullName>CVV__c</fullName>
    <label>CVV</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Exp_Date__c.field-meta.xml
<CustomField>
    <fullName>Exp_Date__c</fullName>
    <label>Exp Date</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registrations__c/recordTypes/Athlete.recordType-meta.xml
<RecordType>
    <fullName>Athlete</fullName>
    <active>true</active>
    <description>Athlete</description>
    <label>Athlete</label>
</RecordType>

force-app/main/default/objects/Registrations__c/recordTypes/COACH.recordType-meta.xml
<RecordType>
    <fullName>COACH</fullName>
    <active>true</active>
    <description>COACH</description>
    <label>COACH</label>
</RecordType>

force-app/main/default/classes/KSAQuotesCtrlTest.cls
@isTest
public class KSAQuotesCtrlTest {
    /*@isTest static void loadKSAQuotesCtrlTest() {
        Account testAccount = new Account();
        testAccount.Name = 'TestAccount';
        insert testAccount;
        
        List<Contact> lstContact = new List<Contact>();
        Contact ct = new Contact();
        ct.FirstName = 'FName123';
        ct.LastName = 'LName123';
        ct.Email = 'fff1223@test.com';
        ct.MobilePhone = '121';
        ct.MailingStreet = 'test.com';
        ct.MailingCity = 'BNG';
        ct.MailingState = 'New';
        ct.MailingPostalCode = '112121';
        ct.AccountId = testAccount.Id;
        lstContact.add(ct);
        
        Contact ct1 = new Contact();
        ct1.FirstName = 'FName123';
        ct1.LastName = 'LName123';
        ct1.Email = 'fff1223@test.com';
        ct1.MobilePhone = '121';
        ct1.MailingStreet = 'test.com';
        ct1.MailingCity = 'BNG';
        ct1.MailingState = 'New';
        ct1.MailingPostalCode = '112121';
        ct1.AccountId = testAccount.Id;
        lstContact.add(ct1);
        insert lstContact;

        fw1__Payment_Plan__c pyt = new fw1__Payment_Plan__c(fw1__Schedule__c='Daily',fw1__Installment_Fee__c=100);
        insert pyt;
        
        List<fw1__Plan_Installment__c> shcedulePayments = new List< fw1__Plan_Installment__c>();
        fw1__Plan_Installment__c plan1 = new fw1__Plan_Installment__c();
        plan1.fw1__Payment_Plan__c = pyt.Id;
        plan1.fw1__Installment_Number__c = 1;
        plan1.fw1__Installment_Percentage__c = 100;
        insert plan1;

        Opportunity opId = new Opportunity(Payment_Plan__c=pyt.Id,AccountId=testAccount.Id,Name = 'ETTest',StageName='Value Proposition',OwnerId=UserInfo.getUserId(),CloseDate = Date.newinstance(2022, 2, 17));
        insert opId;
        opId = [select Id,KSA_Webcode__c from Opportunity where Id=:opId.Id];
        System.assertNotEquals(null, opId.KSA_Webcode__c);
        
        Opportunity opId1 = new Opportunity(Payment_Plan__c=pyt.Id,AccountId=testAccount.Id,Name = 'ETTest12',StageName='Closed Lost',OwnerId=UserInfo.getUserId(),CloseDate = Date.newinstance(2022, 2, 17));
        insert opId1;
        
        opId1 = [select id,KSA_Webcode__c from Opportunity where id=:opId.Id];
        System.assertNotEquals(null, opId1.KSA_Webcode__c);

        Quote__c qte = new Quote__c(Contact__c=ct.Id,Card_Type__c='American Express',Credit_Card_Number__c='370000000000002',CVV__c='000',
                                    Exp_Date__c='',Opportunity__c=opId.Id,Paid_Amount__c=1999.0);
        insert qte;
        Quote__c qte1 = new Quote__c(Contact__c=ct1.Id,Card_Type__c='American Express',Credit_Card_Number__c='370000000000002',CVV__c='000',
                                     Exp_Date__c='',Opportunity__c=opId1.Id,Paid_Amount__c=1999.0, Quote_By__c = 'COACH', is_Head_Coach__c = true);
        insert qte1;
        
        //String athRec = Schema.getGlobalDescribe().get('Registrations__c').getDescribe().getRecordTypeInfosByName().get('Athlete').getRecordTypeId();
        List<Registrations__c> lstRegistrations = new List<Registrations__c>();
        Registrations__c reg = new Registrations__c();
        reg.Opportunity__c = opId1.Id;
        reg.First_Name__c = 'Test';
        reg.Last_Name__c = 'Test Last Name';
        //reg.RecordTypeId = athRec;
        reg.Quote__c = qte1.Id;
        insert reg;

        
 		Test.startTest();
        Set<String> setWebCodeIds = new Set<String>();
        setWebCodeIds.add(opId.KSA_Webcode__c);
       	KSAQuotesCtrl.getQuotes(String.valueOf(ct1.Id));
        Map<String, List<Quote__c>> mapQuote = KSAQuotesCtrl.getQuotesForCoach(setWebCodeIds, String.valueOf(ct1.Id));
        List<fw1__Invoice__c> lstInvoice = KSAQuotesCtrl.getInvoices(String.valueOf(ct1.Id));
        List<fw1__Invoice__c> lstManualInvoice = KSAQuotesCtrl.getManualInvoices(String.valueOf(ct1.Id));
        KSAQuotesCtrl.getCoachEventInfo(String.valueOf(ct1.Id));
        KSAQuotesCtrl.getRoomingListInfo(String.valueOf(opId1));
        KSAQuotesCtrl.codeCoverage();
        //KSAQuotesCtrl.getInvoiceLine(String.valueOf(lstInvoice.get(0).Id));
        //KSAQuotesCtrl.getPaymentInfo(String.valueOf(lstManualInvoice.get(0).Id));
        Test.stopTest();
    }*/
}