force-app/main/default/objects/Opportunity/fields/KSA_Webcode__c.field-meta.xml
<CustomField>
    <fullName>KSA_Webcode__c</fullName>
    <formula>X2_Digit_Year__c + Sport_Abbreviation__c + Code_Auto_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>KSA Webcode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan</label>
    <referenceTo>fw1__Payment_Plan__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Webcode__c.field-meta.xml
<CustomField>
    <fullName>Webcode__c</fullName>
    <externalId>true</externalId>
    <label>Webcode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>KSA Quote</label>
    <nameField>
        <displayFormat>Q-{0000000}</displayFormat>
        <label>Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>American Express</fullName>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
            <value>
                <fullName>MasterCard</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Registration_Opportunities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/CVV__c.field-meta.xml
<CustomField>
    <fullName>CVV__c</fullName>
    <label>CVV</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Registration_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount__c</fullName>
    <label>Paid Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan</label>
    <referenceTo>fw1__Payment_Plan__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registrations__c/Registrations__c.object-meta.xml
<CustomObject>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{0}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registrations__c/fields/Birth_Date__c.field-meta.xml
<CustomField>
    <fullName>Birth_Date__c</fullName>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>American Express</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
            <value>
                <fullName>MasterCard</fullName>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/CVV__c.field-meta.xml
<CustomField>
    <fullName>CVV__c</fullName>
    <label>CVV</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Exp_Date__c.field-meta.xml
<CustomField>
    <fullName>Exp_Date__c</fullName>
    <label>Exp Date</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Relationship_to_Athlete__c.field-meta.xml
<CustomField>
    <fullName>Relationship_to_Athlete__c</fullName>
    <label>Relationship to Athlete</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Coach</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Room_No__c.field-meta.xml
<CustomField>
    <fullName>Room_No__c</fullName>
    <label>Room No</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/School_Name__c.field-meta.xml
<CustomField>
    <fullName>School_Name__c</fullName>
    <label>School Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Shirt_Size_25__c.field-meta.xml
<CustomField>
    <fullName>Shirt_Size_25__c</fullName>
    <label>Shirt Size - $25.00</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Small - $25.00</fullName>
            </value>
            <value>
                <fullName>Large - $25.00</fullName>
            </value>
            <value>
                <fullName>Medium - $25.00</fullName>
            </value>
            <value>
                <fullName>Large XL - $25.00</fullName>
            </value>
            <value>
                <fullName>Large XXL - $25.00</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
                <isActive>false</isActive>
                <label>Large</label>
            </value>
            <value>
                <fullName>Large XL</fullName>
                <isActive>false</isActive>
                <label>Large XL</label>
            </value>
            <value>
                <fullName>Large XXXL - $25.00</fullName>
                <isActive>false</isActive>
                <label>Large XXXL - $25.00</label>
            </value>
            <value>
                <fullName>Medium</fullName>
                <isActive>false</isActive>
                <label>Medium</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Sport__c.field-meta.xml
<CustomField>
    <fullName>Sport__c</fullName>
    <label>Sport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Baseball</fullName>
            </value>
            <value>
                <fullName>Boys Basketball</fullName>
            </value>
            <value>
                <fullName>Boys Lacrosse</fullName>
            </value>
            <value>
                <fullName>Cheer and Dance</fullName>
            </value>
            <value>
                <fullName>Chorus</fullName>
            </value>
            <value>
                <fullName>Cross Country</fullName>
            </value>
            <value>
                <fullName>Field Hockey</fullName>
            </value>
            <value>
                <fullName>Football</fullName>
            </value>
            <value>
                <fullName>Girls Basketball</fullName>
            </value>
            <value>
                <fullName>Girls Lacrosse</fullName>
            </value>
            <value>
                <fullName>Girls Leadership</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Instrumental</fullName>
            </value>
            <value>
                <fullName>Music</fullName>
            </value>
            <value>
                <fullName>Softball</fullName>
            </value>
            <value>
                <fullName>Tennis</fullName>
            </value>
            <value>
                <fullName>Track and Field</fullName>
            </value>
            <value>
                <fullName>Volleyball</fullName>
            </value>
            <value>
                <fullName>Wrestling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registrations__c/fields/Webcode__c.field-meta.xml
<CustomField>
    <fullName>Webcode__c</fullName>
    <inlineHelpText>If Applicable or School Name</inlineHelpText>
    <label>Webcode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registrations__c/recordTypes/Athlete.recordType-meta.xml
<RecordType>
    <fullName>Athlete</fullName>
    <active>true</active>
    <description>Athlete</description>
    <label>Athlete</label>
</RecordType>

force-app/main/default/classes/KSA_PaymentCtrlTest.cls
@isTest
public class KSA_PaymentCtrlTest {
   /* @isTest static void loadKSA_PaymentCtrlTest() {
        //fw1__Payment_Processor__c x = new fw1__Payment_Processor__c(Name = 'PayPal Payments Pro');
        //insert x; 
        
        Account testAccount = new Account();
        testAccount.Name = 'TestAccount';
        insert testAccount;

        Contact ct = new Contact();
        ct.FirstName = 'FName123';
        ct.LastName = 'LName123';
        ct.Email = 'fff1223@test.com';
        ct.MobilePhone = '121';
        ct.MailingStreet = 'test.com';
        ct.MailingCity = 'BNG';
        ct.MailingState = 'New';
        ct.MailingPostalCode = '112121';
        ct.AccountId = testAccount.Id;
        
        insert ct;
        system.debug('CT id: '+ct);
        fw1__Payment_Plan__c pyt = new fw1__Payment_Plan__c(fw1__Schedule__c='Daily',fw1__Installment_Fee__c=100);
        insert pyt;
        Opportunity opId = new Opportunity(Payment_Plan__c=pyt.Id,AccountId=testAccount.Id,Name = 'ETTest',StageName='Value Proposition',OwnerId=UserInfo.getUserId(),CloseDate = Date.newinstance(2022, 2, 17));
        insert opId;
        opId = [select Id,KSA_Webcode__c from Opportunity where Id=:opId.Id];
        System.assertNotEquals(null, opId.KSA_Webcode__c);
        Opportunity opId1 = new Opportunity(Payment_Plan__c=pyt.Id,AccountId=testAccount.Id,Name = 'ETTest12',StageName='Closed Lost',OwnerId=UserInfo.getUserId(),CloseDate = Date.newinstance(2022, 2, 17));
        insert opId1;
        opId1 = [select id,KSA_Webcode__c from Opportunity where id=:opId.Id];
        System.assertNotEquals(null, opId1.KSA_Webcode__c);

        Quote__c qte = new Quote__c(Contact__c=ct.Id,Card_Type__c='American Express',Credit_Card_Number__c='370000000000002',CVV__c='000',
                                   Exp_Date__c='',Opportunity__c=opId.Id,Paid_Amount__c=1999.0);
        insert qte;
        Quote__c qte1 = new Quote__c(Contact__c=ct.Id,Card_Type__c='American Express',Credit_Card_Number__c='370000000000002',CVV__c='000',
                                   Exp_Date__c='',Opportunity__c=opId1.Id,Paid_Amount__c=1999.0);
        insert qte1;
        system.debug('qte id: '+qte);
        
        RecordType rt = [SELECT Id FROM RecordType WHERE sObjectType = 'Registrations__c' AND Name = 'ATHLETE'];
        
        Registrations__c regt = new Registrations__c(Quote__c=qte.Id,School_Name__c='Sch name',Webcode__c='100',
                               Sport__c='Baseball',First_Name__c='Fname',Last_Name__c='Lname',Middle_Name__c='Mname',Gender__c='Male',
                               Birth_Date__c=Date.newinstance(2010, 2, 17),Mobile__c='1212',Email__c='email@test.com',
                               Shirt_Size_25__c='Small - $25.00',Relationship_to_Athlete__c='Self',Room_No__c=1,
                               Contact__c=ct.Id,recordtypeid=rt.Id);
        insert regt;
        Test.startTest();
        //KSA_PaymentCtrl.processPayment(String.valueOf(regt.Id));
        //KSA_PaymentCtrl.getRecordDetails(String.valueOf(regt.Id));
        KSA_PaymentCtrl.processPayment(100, '2121121212', 'March', '2022', '000', 'shg', 'sds', 're', 'we', 'wew', '', 'billingFirstName', 'billingLastName', 'paymentName', null);
        //KSA_PaymentCtrl.processQuotePayment(String.valueOf(qte.Id));
        
        Test.stopTest();
        
    }*/
}